# 引入numpy

In [6]:
import numpy as np

## numpy中的数据创建

In [9]:
# 0维数组（数字）
arr_d_0 = np.array(5)
print(arr_d_0)

# 1维数组
arr_d_1 = np.array([1,2,3])
print(arr_d_1)

# 隐式类型转换--数据的同质性
arr_d_1_1 = np.array([1,'hello'])
print(arr_d_1_1)
arr_d_1_2 = np.array([1,1.5])
print(arr_d_1_2)

# 2维数组
arr_d_2 = np.array([[1,2,3],[4,5,6]])
print(arr_d_2)


5
[1 2 3]
['1' 'hello']
[1.  1.5]
[[1 2 3]
 [4 5 6]]


# ndarry 的基本属性

In [12]:
# 数据维度
print("arr_d_0的数据维度是：",arr_d_0.ndim)
print("arr_d_1的数据维度是：",arr_d_1.ndim)
print("arr_d_2的数据维度是：",arr_d_2.ndim)

# 数据的形状（几行几列）
print("arr_d_2的数据形状是：",arr_d_2.shape)

# 数据的总数量
print("arr_d_2的数据总数量是：", arr_d_2.size)

# 数据的类型
print("arr_d_1_2的数据类型是：", arr_d_1_2.dtype)

arr_d_0的数据维度是： 0
arr_d_1的数据维度是： 1
arr_d_2的数据维度是： 2
arr_d_2的数据形状是： (2, 3)
arr_d_2的数据总数量是： 6
arr_d_1_2的数据类型是： int64


# ndarray 高级属性

In [21]:
# 数组转置
print("arr_d_2的转置是：",arr_d_2.T)

# 单个元素占用的字节数
print("arr_d_2的单个元素占用字节数是：",arr_d_2.itemsize)

# 总内容占用量
print("arr_d_2占用的字节总数是：", arr_d_2.nbytes)

arr_d_2的转置是： [[1 4]
 [2 5]
 [3 6]]
arr_d_2的单个元素占用字节数是： 8
arr_d_2占用的字节总数是： 48


# ndarray的创建方式

In [32]:
# 基础初始化
array = np.array([1,2,3],dtype=int)
print(array)
# 数据拷贝（深拷贝）
array1 = np.copy(array)
print(array1)
array1[0] = 5
print(array1)
print(array)
# 预定义形状,传入的第一个参数是数组的shape，以元组的形式传入，代表几行几列
array = np.zeros((3,4))
print(array)
array1 = np.ones((10,),dtype=int)
print(array1)
array2 = np.full((3,4),'hello')
print(array2)

[1 2 3]
[1 2 3]
[5 2 3]
[1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1 1 1 1 1 1 1 1 1 1]
[['hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello']]


In [36]:
# 已知下限，上限，步进长度（注意这里生成的时候是左闭右开）
array = np.arange(1,10,1)
print(array)

# 已知下限，上限，数据总数，或根据上下限和数据分数，对数据空间进行等分
array = np.linspace(1,10,5)
print(array)

[1 2 3 4 5 6 7 8 9]
[ 1.    3.25  5.5   7.75 10.  ]


In [38]:
# 对数空间，返回在对数空间内均匀间隔的数列  2^0-2^4，对数空间均匀分为5份，也就是2^0,2^1,2^2,2^3,2^4，即在其指数上应该是等差分布的
array = np.logspace(0,4,base=2,num=5)
# 和下面的写法是等效的
array = np.logspace(0,4,5, base=2)
print(array)

[ 1.  2.  4.  8. 16.]


# 特殊矩阵生成方式

In [52]:
# 生成单位矩阵
array = np.eye(3)
print(array)

# 生成对角矩阵
array = np.diag([1,2,3])
print(array)

# 提取主对角线的元素
array = np.arange(1,10,1).reshape((3,3))
array1 = np.diag(array)
print(array1)

# 提取副对角线上的元素,k代表偏移量
array1 = np.diag(array,k=-1)
print(array1)

# 生成0-1之间的随机数（均匀分布）
array = np.random.rand(3,4)
print(array)

# 生成指定范围内的随机数
array = np.random.uniform(3,5,(3,4))
print(array)

# 生成指定范围内的随机整数
array = np.random.randint(3,10,(3,4))
print(array)

# 生成随机数（正态分布）
array = np.random.randn(3,4)
print(array)

# 设置随机数种子,随机数生成时会使用该种子，每次生成的随机数序列保持一致
np.random.seed(10)
array = np.random.randint(1,10,(2,5))
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1 5 9]
[4 8]
[[0.49758556 0.2670731  0.77903442 0.13809544]
 [0.9325291  0.90345913 0.43132077 0.00179876]
 [0.52355134 0.17350579 0.20183266 0.7054101 ]]
[[3.7143404  4.35549654 3.76743892 3.60671122]
 [3.42521717 4.97001374 4.18682733 3.206445  ]
 [3.24549703 4.16889849 3.76257578 4.22191806]]
[[6 6 9 3]
 [4 4 3 8]
 [8 7 7 8]]
[[ 0.41020754 -0.18580567 -0.61218616 -0.55375452]
 [ 1.0929086  -2.15789383 -1.0896814  -1.23073772]
 [ 1.20746668 -0.97659195 -1.60649766 -2.44155179]]
[[5 1 2 1 2]
 [9 1 9 7 5]]
