# 基本函数

In [12]:
import numpy as np

# 平方根
arr = np.sqrt([1,4,9])
print(arr)

# 指数函数（以e为底）
arr = np.exp([1,2])
print(arr)

# 幂函数
arr = np.power([1,2,3],2)
print(arr)

# 自然对数函数（以e为底）
arr = np.log([3])
print(arr)

# 以10为底对数函数
arr = np.log10([100])
print(arr)

# 以10为底对数函数
arr = np.log10([2])
print(arr)

# 以任意数字为底对数函数【需要自己转换】  原理是换底公式：log_a(b) = log_c(b) / log_c(a)
# 下面=log3(5)  以3为底求5的对数
arr = np.log(5) / np.log(3)
print(arr)


# 正余弦(入参为弧度)
arr = np.sin(30)
print(arr)
arr = np.sin(np.pi/6)
print(arr)


# 绝对值
arr = np.array([-1,-2.5,12.1,4.7])
print(np.abs(arr))

# 四舍五入
print(np.round(arr))

# 向上取整
print(np.ceil(arr))

# 向下取整
print(np.floor(arr))

[1. 2. 3.]
[2.71828183 7.3890561 ]
[1 4 9]
[1.09861229]
[2.]
[0.30103]
1.4649735207179269
-0.9880316240928618
0.49999999999999994
[ 1.   2.5 12.1  4.7]
[-1. -2. 12.  5.]
[-1. -2. 13.  5.]
[-1. -3. 12.  4.]
