# 索引和切片

In [20]:
import numpy as np

def my_print(desc, x):
    print(desc + ":\n" +  str(x) + "\n----------------------------------------------------------")


array = np.random.randint(1,100,(3,4))
# 全部
my_print("全部", array)
my_print("全部", array[:])

# 部分  start,stop,step
my_print("部分", array[1:10:2])
my_print("部分，使用slice", array[slice(1, 10, 2)])

# 指定筛选条件
my_print("筛选所有>30且<80的元素", array[(array > 30) & (array < 80)])

# 二维数组中的指定位置上的元素
my_print("二维数组中第2行第4列元素", array[1,3])

# 二维数组中的某一行  array[1] | array[1,] | array[1,:]
my_print("筛选第2行", array[1,])
# 二维数组某一行的指定范围内的元素
my_print("筛选第2行中的前两个元素，index=0和index=1，注意这里也是左闭右开", array[1, 0:2])

# 二维数组中的某一列
my_print("筛选第2列", array[:,1])

# 指定筛选条件
my_print("筛选第2行中>30且<80的元素", array[1][(array[1] > 30) & (array[1] < 80)])


全部:
[[90 80 12 13]
 [36 94 78 92]
 [35 51 97 89]]
----------------------------------------------------------
全部:
[[90 80 12 13]
 [36 94 78 92]
 [35 51 97 89]]
----------------------------------------------------------
部分:
[[36 94 78 92]
 [35 51 97 89]]
----------------------------------------------------------
部分，使用slice:
[[36 94 78 92]
 [35 51 97 89]]
----------------------------------------------------------
筛选所有>30且<80的元素:
[36 78 35 51]
----------------------------------------------------------
二维数组中第2行第4列元素:
92
----------------------------------------------------------
筛选第2行:
[36 94 78 92]
----------------------------------------------------------
筛选第2行中的前两个元素，index=0和index=1，注意这里也是左闭右开:
[36 94]
----------------------------------------------------------
筛选第2列:
[80 94 51]
----------------------------------------------------------
筛选第2行中>30且<80的元素:
[36 78]
----------------------------------------------------------
