# ndarray 运算

In [3]:
import numpy as np


# 一维
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)



[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [11]:
# 二维

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])


print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]


In [14]:
# 行列扩展
c = np.array([1,2,3])  # 一行[1,2,3]
d = np.array([[4],[5],[6]]) # 一列[4,
#                                5,
#                                6]

print(c + d)

'''
c ->  1,2,3
      1,2,3
      1,2,3

d ->  4,4,4
      5,5,5
      6,6,6
'''

[[5 6 7]
 [6 7 8]
 [7 8 9]]


'\nc ->  1,2,3\n      1,2,3\n      1,2,3\n\nd ->  4,4,4\n      5,5,5\n      6,6,6\n'

In [15]:
# 直接和标量做运算等于在每个元素上都与该标量做运算
print(a + 5)
print(a - 5)
print(a * 5)
print(a / 5)

# 和原生数组、元组做运算等于每一行和该数组、元组做运算
print(a + (2,3,4))
print(a + [2,3,4])

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[[0.2 0.4 0.6]
 [0.8 1.  1.2]
 [1.4 1.6 1.8]]
[[ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]
[[ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


# 矩阵运算

In [ ]:
# 点积运算
print(a @ b)
print(np.dot(a,b))